[build]
  publish = "."
  command = ""

[[redirects]]
  from = "/manage-x7k29qz"
  to = "/manage-x7k29qz.html"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
  force = false
